:host = http://localhost:8080
:group-id = 123
:username = bob

# Root
GET :host/

# bad api route
GET :host/api/asdfa

# Create a group
POST :host/api/group/:group-id?turnTime=5

# Get a group
GET :host/api/group/:group-id

# Create a player in a group
POST :host/api/group/:group-id/player/:username

# Create a player in a group
POST :host/api/group/:group-id/player/:username2

# Create a player in a group
POST :host/api/group/:group-id/player/:username3

# Signal the nextturn
POST :host/api/group/:group-id/player/:username/endTurn
